### ISSUE TITLE
Add Ponyville Live! to the homepage

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Poniverse.net#1]
Since Ponyville Live! [merged with Poniverse](http://news.ponyvillelive.com/post/135213219828/ponyville-live-lives-poniverse-and-the-future-of), it should be taken out of our affiliates page and added to the [homepage](https://poniverse.net/).

We'll need an Azura vector drawn. Here's a reference:

![03 - ge6tm2t](https://cloud.githubusercontent.com/assets/1666960/11802944/88d940e2-a2aa-11e5-9690-4547f77ca12b.png)

**Comment by LabLayers** [comment]
It's live! :boom:

https://poniverse.net

![image](https://cloud.githubusercontent.com/assets/607807/11912563/bf8628c2-a60f-11e5-9d13-c0a2b8a12c4b.png)
